### ISSUE TITLE
Add user.updateEmail() and user.updatePhoneNumber() methods

### ISSUE THREAD

**Issue by tyrw** [userfront/userfront-core#113]
We want a logged in user to be able to update their own email and/or phoneNumber via Core JS.

```js
// Should send an verify link by email
Userfront.user.updateEmail(email);

// Should send a verification code by SMS
Userfront.user.updatePhoneNumber(phoneNumber);
```

These methods should call the [verify an email](https://userfront.com/docs/api-client.html#send-account-verification-email) and [verify a phone number](https://userfront.com/docs/api-client.html#verify-a-phone-number) endpoints, respectively.

### Post-deploy tasks
- [ ] Notify the admin (convo 410)

**Comment by RJFelix** [comment]
Moved to Linear DEV-763
