### ISSUE TITLE
Signup vs. login with email/SMS verification code is a bit confusing

### ISSUE THREAD

**Issue by RJFelix** [userfront/userfront-core#124]
The usage of the `signup` and `login` functions with verification codes is a bit confusing - it doesn't match my expectations given their names & how the functions work with other strategies.

The issue is highlighted in MFA signup/login.

##How I expected it to work

I expected to call `Userfront.signup()` when signing up, and `Userfront.login()` when logging in.

For example, **signing up** with a password and a SMS code:

- `const firstResult = Userfront.signup({ method: "password", email, password })`
- MFA is required: `firstResult.isMfaRequired = true`
- `Userfront.sendVerificationCode({ channel: "sms", phoneNumber ])`
- `const secondResult = Userfront.signup({ method: "verificationCode", channel: "sms", phoneNumber, verificationCode })`
- User is signed up and logged in: `secondResult.tokens = { ... }`

And when **logging in** I expect it to be identical, except with `Userfront.login` instead of `Userfront.signup`.

##How it actually works

- `Userfront.signup({ method: "verificationCode" })` is an undocumented alias to `Userfront.sendVerificationCode`
- We have to call `Userfront.login({ method: "verificationCode" })` to verify, even during a signup flow
  - When thinking of a MFA signup, it's counterintuitive to call `login` for a first factor, before the account exists from the client's perspective
- We can't tell if we're creating a new account or logging in an existing account, and we may unintentionally create a new account if using a verification code for a single factor login

So, when we're building a signup form, sometimes we call `signup`, sometimes we call `login`, and we just have to know the difference. 

##Suggested resolution

...I want to think about this a bit more.

My first instict is to make `signup({ method: "verificationCode" })` verify a code in a signup flow.

That makes `signup` and `login` basically identical in behavior, so maybe they should be consolidated into a `Userfront.auth` function that takes an optional `{ type: "signup" | "login" }` to assert that we are/are not creating a new account and instruct the API to fail otherwise. With the signup/login flag absent, it instructs the API to log in if we've matched existing account details, or create a new account otherwise. There's valid use cases for both approaches. `signup` and `login` can be kept as aliases for `auth({ type: "signup" })` and `auth({ type: "login" })`.

**Comment by tyrw** [comment]
I believe the `verificationCode` behavior should mimic the `link` behavior:

```
// Sign up a user and send them a link
Userfront.signup({
  method: "password",
  email: "user@example.com",
  password: "testmodepassword",
});

// Login with the link credentials
Userfront.login({
  method: "link",
  token: token,
  uuid: uuid,
});

// Send a login link for an existing user
Userfront.sendLoginLink("user@example.com");
```

So the equivalent would be:

```
// Sign up a user and send them a verification code
Userfront.signup({
  method: "verificationCode",
  channel: "email", // potentially optional
  email: "user@example.com",
  phoneNumber: "+12345678910" // optional
});

// Login with the verification code
Userfront.login({
  method: "verificationCode",
  channel: "email", // potentially optional
  verificationCode: "123456"
});

// Send a verification code for an existing user
Userfront.sendVerificationCode("user@example.com"); // or phoneNumber
```

**Comment by RJFelix** [comment]
A difference that makes it confusing to me is - at the login link's destination, we truly don't know whether we're doing a login or a signup, so it's reasonable to declare that `login` is used in that case. But with codes we probably do know, we're in the middle of a login or signup flow, and if it's a MFA signup flow then it's a little counterintuitive to go from `signup` to `login` to `signup` to `login`. 

For example, with the new toolkit forms, since signup and login are basically the same, the "obvious" approach for me was to share logic, have `form.type = "login" | "signup"`, then call `Userfront[form.type]({ method, ...formData })`. If it's a login form call `Userfront.login`, if it's a signup form call `Userfront.signup`. It was surprising to find out that doesn't work, and that it actually does something different in the signup case.

**Comment by tyrw** [comment]
It sounds like the underlying issue is that using `login` for the 2nd factor of a signup with MFA required was counterintuitive. If that is correct, I would propose that the solution would be:
- Have the `signup` method pass through the `firstFactorToken`
- When a `firstFactorToken` is included, have the API always handle the request as a login
