### ISSUE TITLE
Support non-browser environments

### ISSUE THREAD

**Issue by RJFelix** [userfront/userfront-core#135]
`@userfront/core` currently only fully supports the browser environment, as it uses Web APIs throughout.

To support non-browser environments, such as React Native or Node, `@userfront/core` would need to:

- [ ] Gate all browser-specific API calls behind a browser check
- [ ] Implement alternatives for the client to provide important information like origin or test/live mode

**Comment by tyrw** [comment]
This would also go nicely with implementing the ability to pass methods for custom redirect and token storage, as those are two of the main differences between browser and non-browser operation on the client. A custom redirect method is proposed [here](https://github.com/userfront/userfront-core/issues/101) for reference

**Comment by RJFelix** [comment]
Moved to Linear DEV-764
