### ISSUE TITLE
NPM failing to install @userfront/core

### ISSUE THREAD

**Issue by jugonzal** [userfront/userfront-core#155]
We are seeing a 500 error when trying to install the userfront/core library via NPM:

```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/@userfront%2fcore - KV GET failed: 401 Unauthorized
```

**Comment by tyrw** [comment]
Thank you for reporting! This was an upstream issue with npm infrastructure that they have since resolved: https://status.npmjs.org/incidents/zdznxkrp22py
