### ISSUE TITLE
`sendLoginLink` exported return type is wrong

### ISSUE THREAD

**Issue by moroshko** [userfront/userfront-core#63]
[`sendLoginLink` returns data](https://github.com/userfront/userfront-core/blob/68aa96c2d8b8f1e11ab01af9aa56e8b461d02bd8/src/signon.js#L272), but [the exported types says it returns void](https://github.com/userfront/userfront-core/blob/68aa96c2d8b8f1e11ab01af9aa56e8b461d02bd8/ts/index.d.ts#L73).

Would be great to properly type this function.

Thanks :)

**Comment by tyrw** [comment]
Updated with `@userfront/core@0.2.32`

**Comment by moroshko** [comment]
@tyrw The updated types do not seem to include possible errors. For example, if you try to login using the email `misha@misha.misha` the response is:
```
{
  error: "Bad Request"
  message: "Email format is invalid"
  statusCode: 400
}
```
which is not assignable to `LinkResponse`.

**Comment by tyrw** [comment]
@moroshko Thanks for the follow up. We're on the fence about switching this library over to typescript (JS encourages readability and contributions from those that don't know TS). That said, it would be less prone to issues like this.

We'll try to add the error responses, and if it's starting to look hard to track, will make an issue to convert to TS so these things are all auto-generated.

**Comment by RJFelix** [comment]
Added to Linear, DEV-757
