### ISSUE TITLE
Replace `axios` with `isomorphic-unfetch` to cut down bundle size

### ISSUE THREAD

**Issue by mikestopcontinues** [userfront/userfront-core#74]
Hey, I'm exploring userfront as an alternative to Auth0. It looks great! This FR isn't a dealbreaker or anything, but `axios` is pretty heavy now that `fetch` and almost complete browser support. `isomorphic-unfetch` fills in the gap, providing `node-fetch` on the server and a really thin polyfill in the browser. Cheers!

**Comment by tyrw** [comment]
@mikestopcontinues Thanks for writing this up. We've had it in mind for a little while and totally agree.

**Comment by RJFelix** [comment]
Moved to Linear DEV-759
